name: crea_chess
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  chessground: ^2.1.0
  cupertino_icons: ^1.0.2
  dartchess: ^0.5.0
  fast_immutable_collections: ^9.1.6
  firebase_core: ^2.21.0
  firebase_database: ^10.3.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^2.4.1
  hydrated_bloc: ^9.1.2
  intl: ^0.18.1
  path_provider: ^2.1.1

dev_dependencies:
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  freezed: ^2.4.5

flutter:
  uses-material-design: true
  generate: true
