// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmEyuz57Xc__pl5qbY-VPyQL1oiqGPbFQ',
    appId: '1:737365859201:web:641712776ff306ec8d6680',
    messagingSenderId: '737365859201',
    projectId: 'crea-chess',
    authDomain: 'crea-chess.firebaseapp.com',
    storageBucket: 'crea-chess.appspot.com',
    measurementId: 'G-5Y9MXTJZWP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFqzeuIa-VFeESo0U9oBGVkzjxo6xTDl0',
    appId: '1:737365859201:android:472bc07b9ec6e5608d6680',
    messagingSenderId: '737365859201',
    projectId: 'crea-chess',
    storageBucket: 'crea-chess.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4x-rraKxcxt5GQ78frV_J5aOPo1HY1Bo',
    appId: '1:737365859201:ios:ece9268689049d718d6680',
    messagingSenderId: '737365859201',
    projectId: 'crea-chess',
    storageBucket: 'crea-chess.appspot.com',
    iosBundleId: 'com.example.creaChess',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4x-rraKxcxt5GQ78frV_J5aOPo1HY1Bo',
    appId: '1:737365859201:ios:ccf6f8c08b0c6e488d6680',
    messagingSenderId: '737365859201',
    projectId: 'crea-chess',
    storageBucket: 'crea-chess.appspot.com',
    iosBundleId: 'com.example.creaChess.RunnerTests',
  );
}
