import 'package:crea_chess/package/atomic_design/color.dart';
import 'package:flutter/material.dart';

class CCInputDecoration extends InputDecoration {
  CCInputDecoration({
    required BuildContext context,
    super.icon,
    super.iconColor,
    super.label,
    super.labelText,
    super.labelStyle,
    super.floatingLabelStyle,
    super.helperText,
    super.helperStyle,
    super.helperMaxLines,
    super.hintText,
    // super.hintStyle,
    super.hintTextDirection,
    super.hintMaxLines,
    super.error,
    super.errorText,
    super.errorStyle,
    super.errorMaxLines,
    super.floatingLabelBehavior,
    super.floatingLabelAlignment,
    super.isCollapsed,
    super.isDense,
    super.contentPadding,
    super.prefixIcon,
    super.prefixIconConstraints,
    super.prefix,
    super.prefixText,
    super.prefixStyle,
    super.prefixIconColor,
    super.suffixIcon,
    super.suffix,
    super.suffixText,
    super.suffixStyle,
    super.suffixIconColor,
    super.suffixIconConstraints,
    super.counter,
    super.counterText,
    super.counterStyle,
    super.focusColor,
    super.hoverColor,
    super.focusedBorder,
    super.focusedErrorBorder,
    super.disabledBorder,
    super.enabled,
    super.semanticCounterText,
    super.alignLabelWithHint,
    super.constraints,
  }) : super(
          border: const OutlineInputBorder(),
          fillColor: CCColor.fieldBackground(context),
          filled: true,
          hintStyle: TextStyle(color: Colors.grey[500]),
        );
}
